# Generated by Django 5.0.3 on 2024-03-25 15:09

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE SCHEMA IF NOT EXISTS content;
            """,
            reverse_sql='DROP SCHEMA content CASCADE;',
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField(unique=True, verbose_name="title")),
                ("text", models.TextField(blank=True, verbose_name="text")),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("added", "Added"),
                            ("done", "Done"),
                            ("in_progress", "Inprogress"),
                        ],
                        default="added",
                        verbose_name="status",
                    ),
                ),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "db_table": 'content"."tasks',
            },
        ),
    ]
